#!/bin/bash
#
# IPsec overlay network manager (l3overlay)
# vagrant/setup-l3overlay - l3overlay provisioning script for Vagrant test environment
#
# Copyright (c) 2017 Catalyst.net Ltd
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -euf -o pipefail

box=$1

install_scripts="/usr/local/sbin"
config_dir="/etc/l3overlay"

if [ -z "${box}" ]
then
    echo "usage: $(basename ${0}) <BOX>"
    exit 1
fi

if [ $(id -u) -ne 0 ]
then
    echo "This script needs root privileges."
    exit 2
fi

add-apt-repository -y ppa:cz.nic-labs/bird
apt-get update

apt-get install -y iproute2
apt-get install -y vlan
apt-get install -y bird
apt-get install -y strongswan
apt-get install -y strongswan-plugin-openssl
apt-get install -y make
apt-get install -y git
apt-get install -y python3-pip
# pip3 install --upgrade setuptools # Needed for Ubuntu 14.04.
pip3 install pyroute2==0.4.6
pip3 install jinja2
pip3 install pylint

service l3overlay stop || true

make -C /vagrant test
make -C /vagrant install systemd-install ETC_DIR="/etc"

echo "Reloading systemctl daemon..."
systemctl daemon-reload

dos2unix /etc/default/l3overlay
# dos2unix /etc/init/l3overlay.conf # Needed for Upstart configuration file.

echo "Removing ${config_dir}... "
rm -rf "${config_dir}"

echo "Creating ${config_dir}... "
mkdir -p "${config_dir}"

echo "Installing /vagrant/vagrant/global.conf to ${config_dir}/global.conf... "
cp /vagrant/vagrant/global.conf "${config_dir}/global.conf"

echo "Installing /vagrant/vagrant/${box}/overlays to ${config_dir}/overlays... "
cp -R "/vagrant/vagrant/${box}/overlays" "${config_dir}/overlays"

service l3overlay start
